### ISSUE TITLE
change lib/core.dart to lib/rx.dart

### ISSUE THREAD

**Issue by lukepighetti** [renggli/dart-rx#1]
Hi there, really interested in what you're doing here. Just a heads up, consumers of this package will expect to be able to use it with `import 'package:rx/rx.dart'`. The entrypoint for this package is not clear otherwise.

**Comment by renggli** [comment]
Thank you for the comments. Feel free to create pull requests.

Note this package is in very early experimentation. I haven't really thought about the package structure. Right now you have to import constructors, operators and the base classes separately. 

Also I am not really sure if this design around separate functions is that great for Dart? I like that we can keep the base classes small and easy to understand. I don't like the complications with the imports, and the lifting ...

**Comment by lukepighetti** [comment]
Yeah to be perfectly honest the constructor functions (`rxjs` style) doesn't fit well with Dart, but there has been a nagging question in the community for a while about if `rxdart` is truly Rx or not due to its dependence on streams, so I'm happy to see someone playing around with something different.

**Comment by renggli** [comment]
As a personal goal I wanted to understand how Rx really works from the inside. 

I never got fully accustomed to Dart Streams, and being used to RxJs and RxJava I didn't really like the existing implementation. I wasn't aware of the discussions you mentioned ...

**Comment by lukepighetti** [comment]
closed in https://github.com/renggli/dart-rx/commit/218c536cd6afcee4d974526b8274c55babf8f108
