### ISSUE TITLE
How to integrate library with API call like Retrofit on Java/kotlin

### ISSUE THREAD

**Issue by HDCong** [renggli/dart-rx#11]
- First of all, thanks for your nice repo.
- In my case, i need to call the restful app then return the `Observable<Result>` when complete via emiter like Rxjava into `onNext`, `onError` or `complete`
- The Issuse I meet is I can't make the API call with network without await / async keywork. If the functioin has `await` keyword, it require `async` keyword then Future required. But exactly type we need in return is `Observable<Result>`
Bellow is my code. I need function `getUserObservable` return `<Observable<UserResponse>>` instead Future

**Comment by renggli** [comment]
Convert the future to an observable, the use RX operators to transform, handle errors, etc.

```dart
Observable<UserResponse> getUserObservable() =>
    _dio.get(_endpoint).toObservable()
        .map(response => UserResponse.fromJson(response.data));
```

**Comment by HDCong** [comment]
> Convert the future to an observable, then use RX operators to transform, handle errors, etc.
> 
> ```dart
> Observable<UserResponse> getUserObservable() =>
>     _dio.get(_endpoint).toObservable()
>         .map(response => UserResponse.fromJson(response.data));
> ```

I can't find `toObservable` function. Could you please more details.
Thanks!

**Comment by HDCong** [comment]
![image](https://user-images.githubusercontent.com/48685869/69910188-9bee5280-1439-11ea-96d1-92fad23041fc.png)
The IDE notice me

**Comment by HDCong** [comment]
Can't find the `toObservable` because my library version is 0.0.3. Upgrade to `0.0.4` and it work!
Thanks @renggli

**Comment by HDCong** [comment]
One more thing, How can I do the late function after observable complete like `flatMap`.
Example:
Observable<UserResponse> getUserObservable() =>
    _dio.get(_endpoint).toObservable()
        .map(response => UserResponse.fromJson(response.data)).flatMap((user)=>otherObservableCall())

**Comment by renggli** [comment]
Not sure what you mean by _do the late function_?

**Comment by HDCong** [comment]
That mean I have more than one function.
The second function will call after the first function complete. The Thirt function call after second complete
In Java or kotlin we have flatmap. How can I do it with this library

**Comment by renggli** [comment]
Ahh, `flatMap` is conceptually the same as the more generic `mergeMap` (https://github.com/renggli/dart-rx/blob/362efafaf43986408b8041259f85d1257eeb96e2/lib/src/operators/merge.dart#L31). I should probably add an alias for `flatMap`, because this is such a well known name ...

**Comment by HDCong** [comment]
Thanks in advanced!!
