### ISSUE TITLE
nit: remove $ from examples

### ISSUE THREAD

**Issue by lukepighetti** [renggli/dart-rx#3]
Idiomatic dart doesn't use `$` for streams since we have had a strongly typed language from the beginning. While use of `$` is common in JavaScript it is very uncommon in Dart. Just a minor nit. I only bring it up because people without `rxjs` experience will be confused by this use of `$`

**Comment by renggli** [comment]
I agree, I don't like the `$` either. Problem is that the constructors are named the same as their constructors. Alternative in 1036fe9ab6d0867674df78dbdd3b67fcf048e43b.

**Comment by lukepighetti** [comment]
Okay yeah, I get it now. I have some ideas that I will explain through PR...
