### ISSUE TITLE
nit: no support for async generators

### ISSUE THREAD

**Issue by lukepighetti** [renggli/dart-rx#6]
Just posting this up for discussion. One of the problems with not extending Dart streams is you lose access to features like async generators.

https://www.youtube.com/watch?v=TF-TBsgIErY&t=4m43s

**Comment by lukepighetti** [comment]
Woop, you can use `fromStream`

**Comment by renggli** [comment]
Yeah, or you could convert an `Iterable`, e.g.

- `fromIterable(IntegerRange(0, 100))` using the ranges from the `more` library (as in the example), or
- `fromIterable(Iterable.generate(i, (i) -> i).take(100))` using only built-in functionality from Dart.
